x-moq: &x-moq
  build: .
  volumes:
    - ./dev/localhost.crt:/etc/tls/cert:ro
    - ./dev/localhost.key:/etc/tls/key:ro
    - certs:/etc/ssl/certs
  depends_on:
    install-certs:
      condition: service_completed_successfully

services:
  relay1:
    <<: *x-moq
    entrypoint: moq-relay
    command: --tls-cert /etc/tls/cert --tls-key /etc/tls/key --tls-disable-verify --cluster-node relay1 --cluster-root relay1 --dev
    ports:
      - "127.0.0.1:4443:443"
      - "127.0.0.1:4443:443/udp"
    networks:
      - isolated_network
    cap_add:
      - NET_ADMIN

  relay2:
    <<: *x-moq
    entrypoint: moq-relay
    command: --tls-cert /etc/tls/cert --tls-key /etc/tls/key --tls-disable-verify --cluster-node relay2 --cluster-root relay1 --dev
    depends_on:
      - relay1
    ports:
      - "127.0.0.1:4444:443"
      - "127.0.0.1:4444:443/udp"
    networks:
      - isolated_network
    cap_add:
      - NET_ADMIN

  relay3:
    <<: *x-moq
    entrypoint: moq-relay
    command: --tls-cert /etc/tls/cert --tls-key /etc/tls/key --tls-disable-verify --api http://api --node https://relay3 --dev --announce https://dir
    depends_on:
      - relay2
    ports:
      - "127.0.0.1:4445:443"
      - "127.0.0.1:4445:443/udp"
    networks:
      - isolated_network
    cap_add:
      - NET_ADMIN

  pub:
    <<: *x-moq
    entrypoint: moq-bbb
    command: --tls-disable-verify --broadcast bbb --url https://relay1
    depends_on:
      - relay1
    networks:
      - isolated_network

  install-certs:
    image: golang:latest
    working_dir: /work
    command: go run filippo.io/mkcert -install
    environment:
      CAROOT: /work/caroot
    volumes:
      - ${CAROOT:-.}:/work/caroot
      - certs:/etc/ssl/certs
      - ./dev/go.mod:/work/go.mod:ro
      - ./dev/go.sum:/work/go.sum:ro
    networks:
      - isolated_network

networks:
  isolated_network:
    driver: bridge
    internal: true

volumes:
  certs:
